package {

    // Test to ensure dynamic boxed cast of null literal is not generating invalid IL code

    public class EvilClass {

        public function EvilClass(a:Object, b:Object) {
            trace("" + a + b);
        }

    }

    // Test invalid id generated by passing a null after dynamic param
    public class Test {

        public static function invalid():void {
            var dyn:Object;
            var successResponse:EvilClass = new EvilClass(dyn, null);
        }

        public static function Main():int {
            invalid();

            return 0;
        }

    }

}

