#!/bin/sh
exec /Library/Frameworks/Mono.framework/Versions/2.10.9/bin/mono ./mcs.exe /noconfig -sdk:4 "-lib:/Users/benjcooley/projects/mono/mcs/class/lib/net_4_0" "$@" -r:System.dll -r:System.Core.dll -r:Microsoft.CSharp.dll 
