#!/bin/sh
exec /Library/Frameworks/Mono.framework/Versions/2.10.9/bin/mono ./mcs.exe /noconfig -sdk:4 "-lib:/Library/Frameworks/Mono.framework/Versions/2.10.9/lib/mono/4.0/" "$@" -r:System.dll -r:System.Core.dll -r:Microsoft.CSharp.dll 
