#!/bin/sh
exec /Library/Frameworks/Mono.framework/Versions/2.10.9/bin/mono $MONO_OPTIONS mcs.exe -lib:/Library/Frameworks/Mono.framework/Versions/2.10.9/lib/mono/2.0 -lib:/Library/Frameworks/Mono.framework/Versions/2.10.9/lib/mono/3.5 "$@"
