thisdir = class/PlayScript.Optimization
include ../../build/rules.make

LIBRARY = PlayScript.Optimization.dll
LIBRARY_SNK = ../mono.snk

LIB_MCS_FLAGS = -r:System.dll -unsafe

NO_TEST = yes

include ../../build/library.make
